services:
  app:
    container_name: loansapplication
    image: loansapplication
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loanapplications.com  
      PGADMIN_DEFAULT_PASSWORD: 12345678
    depends_on:
      - dbpostgresql
